name: Build and Publish to NuGet

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Bump version in csproj
        id: bump_version
        shell: pwsh
        run: |
          $csproj = 'OracleDBReader.csproj'
          [xml]$xml = Get-Content $csproj
          $versionNode = $xml.Project.PropertyGroup.Version
          $oldVersion = $versionNode.'#text'
          $parts = $oldVersion -split '\.'
          $parts[2] = [int]$parts[2] + 1
          $newVersion = "$($parts[0]).$($parts[1]).$($parts[2])"
          $versionNode.'#text' = $newVersion
          $xml.Save($csproj)
          echo "::set-output name=new_version::$newVersion"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump version to ${{ steps.bump_version.outputs.new_version }}
          branch: main
          file_pattern: OracleDBReader.csproj
